version: 2.1

jobs:
    build:
        docker:
            - image: 889883130442.dkr.ecr.us-west-2.amazonaws.com/fair-images:python-3.7.1
        steps:
            - checkout
            - run:
                name: activate venv
                command: source venv/bin/activate
            - run:
                name: install requirements
                command: pip install -r requirements.txt
    lint:
        steps:
            
            - run:
                name: run flake8 linter
                command: flake8 --max-line-length=120 --extend-ignore=E402

workflows: 
    lint:
        jobs:
            - build
            - lint
