version: 2.1

jobs:
    lint:
        docker:
            - image: circleci/python:3.8.2
        resource_class: small
        steps:
            - checkout
            - restore_cache:
                  key: packages2-{{ checksum "requirements.txt" }}
            - run:
                  name: Create Virtual Environment
                  command: python3 -m venv venv
            - run:
                  name: Activate Virtual Environment
                  command: source venv/bin/activate
            - run:
                  name: pip Install requirements
                  command: pip install -r requirements.txt
            - save_cache:
                  key: packages2-{{ checksum "requirements.txt" }}
                  paths:
                      - "venv"
            - run:
                  name: Run the Linter
                  command: python3 -m flake8 helphours --max-line-length=120 --extend-ignore=E402

workflows:
    build_and_lint:
        jobs:
            - lint
