version: 2.1

jobs:
    lint:
        docker:
            - image: circleci/python:3.8.2
        steps:
            - checkout
            - run:
                  name: create venv
                  command: python3 -m venv venv
            - run:
                  name: activate venv
                  command: source venv/bin/activate
            - run:
                  name: install requirements
                  command: pip install -r requirements.txt
            - run:
                  name: debug
                  command: pwd && ls
            - run:
                  name: run flake8 linter
                  command: python3 -m flake8 helphours --max-line-length=120 --extend-ignore=E402

workflows:
    build_and_lint:
        jobs:
            - lint
